### ISSUE TITLE
Utilisation

### ISSUE THREAD

**Issue by JohnDoeJD** [baptistedph/carrefour-products-api#1]
Bonjour,
On ne se connait pas mais j'ai vu votre projet carrefour sur votre github. j'aurais besoin d'un peu de votre temps pour comprendre comment il fonctionne svp. Je possède discord si c'est plus pratique pour vous.  Pourriez vous m'accorder juste quelques minutes si possible svp?
En vous remerciant, cordialement.

**Comment by baptistedph** [comment]
Bonjour,
Tout d'abord, désolé pour ma réponse tardive.
Pour utiliser l'API, il vous suffit de lancer un browser (grâce à puppeteer) avec la commande npm start. 
Ensuite, vous devez fetch sur l'endpoint /products?q=[keywords] comme indiqué dans le readme.
